# Generated by Django 4.1.7 on 2023-04-04 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='entrepreneur',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booked_schedules', to=settings.AUTH_USER_MODEL, verbose_name='予約者'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='available_schedules', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
    ]
